import React from 'react';
import { Cats } from './Cats';

export const Adoption = () => {
  const cats = [
    {
      _id: '6428bde8baf75b80f5c9ef51',
      img: 'https://plus.unsplash.com/premium_photo-1677545182425-4fb12bdb9faf?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=2072&q=80',
      name: 'Trevor',
      age: 70,
      neutered: true,
      microchipped: true,
      children: false,
      colour: 'blond',
      environment: 'indoor',
      personality: 'timid',
      vaccinated: true,
      sex: 'female',
      other_pets: true,
      description:
        'Trevor is a handsome lad of 5/6 years young, he has been neutered, microchipped,fully vaccinated and has also had dental treatment that was required. He is a bit of a timid lad until he gets to know you but will flourish with an understanding home on his own where he can be very spoilt and no young children sorry',
      available: '2023-04-03T12:04:19.531Z',
    },
    {
      _id: '6428bf84baf75b80f5c9ef52',
      img: 'https://images.unsplash.com/photo-1514888286974-6c03e2ca1dba?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1443&q=80',
      name: 'Sausage',
      age: null,
      neutered: null,
      microchipped: null,
      children: null,
      colour: 'black and white',
      environment: null,
      personality: null,
      vaccinated: true,
      sex: 'male',
      other_pets: null,
    },
    {
      _id: '6428c07cbaf75b80f5c9ef53',
      img: 'https://media.istockphoto.com/id/1333388556/photo/shocked-orange-thai-cat-cat-lying-sideways-on-background-shocked-cat.jpg?s=1024x1024&w=is&k=20&c=FWSQ6pWTqJvBs-PMd-zTgwPqzpdhSOffKvOUxIpt8ts=',
      name: 'Nora Batty',
      age: 24,
      neutered: null,
      microchipped: null,
      children: true,
      colour: 'black and white',
      environment: 'indoor',
      personality: 'timid',
      vaccinated: true,
      sex: 'female',
      other_pets: true,
    },
    {
      _id: '6428bde8baf75b80f5c9ef57',

      name: 'Trevor',
      age: 70,
      neutered: true,
      microchipped: true,
      children: false,
      colour: 'blond',
      environment: 'indoor',
      personality: 'timid',
      vaccinated: true,
      sex: 'female',
      other_pets: true,
    },
    {
      _id: '6428bf84baf75b80f5c9ef78',

      name: 'Sausage',
      age: null,
      neutered: null,
      microchipped: null,
      children: null,
      colour: 'black and white',
      environment: null,
      personality: null,
      vaccinated: true,
      sex: 'male',
      other_pets: null,
    },
    {
      _id: '6428c07cbaf75b80f5c9ef58',

      name: 'Nora Batty',
      age: 24,
      neutered: null,
      microchipped: null,
      children: true,
      colour: 'black and white',
      environment: 'indoor',
      personality: 'timid',
      vaccinated: true,
      sex: 'female',
      other_pets: true,
    },
    {
      _id: '6428bde8baf75b80f5c9ef54',

      name: 'Trevor',
      age: 70,
      neutered: true,
      microchipped: true,
      children: false,
      colour: 'blond',
      environment: 'indoor',
      personality: 'timid',
      vaccinated: true,
      sex: 'female',
      other_pets: true,
    },
    {
      _id: '6428bf84baf75b80f5c9ef55',

      name: 'Sausage',
      age: null,
      neutered: null,
      microchipped: null,
      children: null,
      colour: 'black and white',
      environment: null,
      personality: null,
      vaccinated: true,
      sex: 'male',
      other_pets: null,
    },
    {
      _id: '6428c07cbaf75b80f5c9ef56',

      name: 'Nora Batty',
      age: 24,
      neutered: null,
      microchipped: null,
      children: true,
      colour: 'black and white',
      environment: 'indoor',
      personality: 'timid',
      vaccinated: true,
      sex: 'female',
      other_pets: true,
    },
  ];
  return (
    <section>
      <Cats cats={cats} />
    </section>
  );
};
